import styled from "@emotion/styled";
import glass from "./assets/glass.png"
import title from "./assets/text.png"
/**
 * SimpleLandingPage
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function Example() {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <SimpleLandingPage />
 *     </>
 *   );
 * }
 * ```
 * ---
 * @params {any} props - This widget does not require props. You can pass custom dynamic props to the widget as you want (in TypeScript, it will raise type check issues).
 * ---
 * @preview
 * ![](grida://assets-reservation/images/2:11)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (acknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : unknown://undefined/2:11 -->
 */
export default function SimpleLandingPage() {
  return (
    <RootWrapper>
      <TopPage>
        <HamburgerMenuIcon>
          <HamburgerRectangle1 />
          <HamburgerRectangle2 />
          <HamburgerRectangle3 />
        </HamburgerMenuIcon>
        <NaturbarsLogo src={title} alt="image of NaturbarsLogo" />
        <SearchIcon>
          <SearchRectangle />
          <SearchEllipse1 />
          <SearchEllipse2 />
        </SearchIcon>
      </TopPage>
      <ContainerImage>
        <ImageWrapper>
          <ContainerRectangles>
            <Rectangle6/>
          
            <Rectangle7/>
          </ContainerRectangles>

          <HoldingGlassPng src={glass} alt="image of HoldingGlassPng" />
        </ImageWrapper>

        <SimpleEasyHealthy>
          Simple,
          <br />
          Easy,
          <br />
          Healthy.
        </SimpleEasyHealthy>
      </ContainerImage>
    </RootWrapper>
  );
}

const RootWrapper = styled.div`
  min-height: 100vh;
  background-color: white;
  display: flex;
  flex-direction: column;
`;

const TopPage = styled.div`
  display: flex;
  justify-content: space-between;
  padding: 2rem;
`

const HoldingGlassPng = styled.img`
  width: 500px;
  height: 587px;
`;

const ContainerImage = styled.div`
  display: flex;
  background-color: blue;
  margin-top: 13rem;
  margin-left: 35%;
`

const HamburgerMenuIcon = styled.div`
  display: flex;
  flex-direction: column;
  width: 50px;
  height: 40px;
  left: 115px;
  top: 89px;
  gap: 5px
`;

const HamburgerRectangle1 = styled.div`
  width: 50px;
  height: 8px;
  background-color: black;
  border-radius: 6px;
  left: 0px;
  top: 8px;
`;

const HamburgerRectangle2 = styled.div`
  width: 35px;
  height: 8px;
  background-color: black;
  border-radius: 6px;
  left: 0px;
  top: 24px;
`;

const HamburgerRectangle3 = styled.div`
  width: 50px;
  height: 8px;
  background-color: black;
  border-radius: 6px;
  left: 0px;
  top: 40px;
`;

const NaturbarsLogo = styled.img`
  width: 413px;
  height: 67px;
  object-fit: cover;
  left: 1073px;
  top: 86px;
`;

const SearchIcon = styled.div`
  width: 41px;
  height: 42px;
`;

const SearchRectangle = styled.div`
  width: 35px;
  height: 8px;
  background-color: black;
  border-radius: 6px;
  transform: rotate(-315deg);
  transform-origin: top left;
`;

const SearchEllipse1 = styled.div`
  width: 31px;
  height: 31px;
  background-color: black;
  border-radius: 31px / 31px;
`;

const SearchEllipse2 = styled.div`
  width: 17px;
  height: 17px;
  background-color: white;
  border-radius: 17px / 17px;
`;

const SimpleEasyHealthy = styled.div`
  color: black;
  text-overflow: ellipsis;
  font-size: 64px;
  font-family: Inter, sans-serif;
  font-weight: initial;
  text-align: right;
  background-color: red;
`;

// const SimpleEasyHealthy = styled.div`
//   color: black;
//   position: absolute;
//   text-overflow: ellipsis;
//   font-size: 64px;
//   font-family: Inter, sans-serif;
//   font-weight: initial;
//   text-align: right;
//   bottom: 490px;
//   left: 1130px;
//   background-color: red;
// `;

const ContainerRectangles = styled.div`
  position:absolute
  bottom: 10px;
`

const Rectangle6 = styled.div`
  position: absolute;
  bottom: 550px;
  left: 400px;
  width: 8px;
	height: 101px;
	background-color: black;
	transform: rotate(-340deg);
	transform-origin: top left;
`;

const Rectangle7 = styled.div`
  position: absolute;
  bottom: 592px;
  left: 400px;
  width: 8px;
	height: 51px;
	background-color: black;
	transform: rotate(-90deg);
	transform-origin: top left;
`;

const ImageWrapper = styled.div`
  position: relative;
`;